# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinfo',
            name='collect_id',
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
        migrations.DeleteModel(
            name='ClassInfo',
        ),
        migrations.DeleteModel(
            name='CollegeInfo',
        ),
    ]
