# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_auto_20171208_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=255, verbose_name='班级名称')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=255, verbose_name='学院名称')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('stu_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('stu_name', models.CharField(max_length=100, verbose_name='姓名')),
                ('stu_no', models.CharField(max_length=50, verbose_name='身份证')),
                ('stu_img', models.CharField(max_length=255, verbose_name='照片路径')),
                ('createTime', models.DateTimeField(verbose_name='注册时间')),
                ('stu_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_stu', to='student.ClassInfo')),
            ],
        ),
        migrations.AddField(
            model_name='classinfo',
            name='collect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_class', to='student.CollegeInfo'),
        ),
    ]
