# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20171208_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinfo',
            name='collect',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='stu_class',
        ),
        migrations.DeleteModel(
            name='ClassInfo',
        ),
        migrations.DeleteModel(
            name='CollegeInfo',
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
