# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0008_auto_20171212_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=255, null=True, verbose_name='班级名称')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=255, null=True, verbose_name='学院名称')),
            ],
        ),
        migrations.CreateModel(
            name='Image_Collect',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_src', models.CharField(max_length=255, null=True, verbose_name='照片地址')),
                ('image_title', models.CharField(max_length=255, null=True, verbose_name='照片标题')),
                ('createTime', models.DateTimeField(null=True, verbose_name='拍摄时间')),
                ('creator', models.CharField(max_length=255, null=True, verbose_name='上传人')),
                ('stu_class', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_image', to='student.ClassInfo')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('stu_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('stu_name', models.CharField(max_length=100, null=True, verbose_name='姓名')),
                ('stu_cnname', models.CharField(max_length=255, null=True, verbose_name='姓名拼音')),
                ('stu_no', models.CharField(max_length=50, null=True, verbose_name='身份证')),
                ('stu_img', models.CharField(max_length=255, null=True, verbose_name='照片路径')),
                ('stu_bir', models.DateField(null=True, verbose_name='生日')),
                ('stu_sex', models.NullBooleanField(verbose_name='性别')),
                ('stu_phone', models.CharField(max_length=100, null=True, verbose_name='手机号')),
                ('stu_qq', models.CharField(max_length=100, null=True, verbose_name='QQ号')),
                ('stu_wechat', models.CharField(max_length=100, null=True, verbose_name='微信')),
                ('stu_home', models.CharField(max_length=255, null=True, verbose_name='现居地')),
                ('stu_desc', models.CharField(max_length=255, null=True, verbose_name='个人简介')),
                ('stu_password', models.CharField(max_length=255, null=True, verbose_name='登陆密码')),
                ('stu_about', models.CharField(max_length=255, null=True, verbose_name='班级感言')),
                ('createTime', models.DateTimeField(null=True, verbose_name='注册时间')),
                ('stu_class', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_stu', to='student.ClassInfo')),
            ],
        ),
        migrations.AddField(
            model_name='classinfo',
            name='collect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_class', to='student.CollegeInfo'),
        ),
    ]
